apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: test-secret
  namespace: sealed-secrets
spec:
  encryptedData:
    dummykey1: AgBZJufhCcyxGBinCRYcAQarf8I+PLI2yi1jiSzYUudOQdrNf4aymRRI7Y20L1a3y0FyOOmtPs0lsMjlUb+MpaAgoyY1fSxiCX2Uuyk+3ZxOHFg5V/DVvy3yg+HaofHXedcF3hISYOCJCe2Dst34K05M32EmGnFanGm8JxObH04W79nAH1l8b/qHt1XDBtSyIFEA9bkT6q9vC88wifK5hv6w7xoz4QGyZpR4anpkymrGFn0HFyKz0pYQBaaEQn2rz7D+9TTGTPQ2EBpgC5pizyAkjrV1dhuaYZc/h1FgQj+9xj3GzhNdBDs8StpLfDqfDmteWHmk40zlNM+9LAUYouXO8Rbgwsz3NmViY/4oVQgB+l6R2sWcMTyVQ7XYhh79wdzvb0GvWb66x/F4B8LRYit2G0Ahy+clEBgMZ4qYmRtGi8eufYnkBw8IZc4t/M7NE4LFRHUtE8TdIq82GeAV9ZheKPkUoonnoTz+rG4li2hIJvP2yjT9IWHgVbH67TFOlmocrCh0aF2kV0h+d53M/suF0RDeKYm8kzT/eWq3Jvl9IcHrJpL+2+0uS0j+UYmt0MwPKBQjKveK/2k951okP6EuO8cKkPtPEBHyBqZ+xUXVaJpcEF2AD41MSri6ay0Q/5FxPUmT9rjAwt9edNKGHhCRJ25r0t6WAgBqUTy+3P3JVSgx20pUKvlQpsFtvLcGk8yqwPlo+BAM97Zq9w==
    dummykey2: AgAAAzbTzfqroIJjnaiGm4zvbOfpS6qCQJeFnrq7uwBmv7YXhms8iPsbzO2tgaTMZSf8YPWweqQk6v0xAKtBchVuBvHIc9a8jmMBa5I+shJ/xJsXPXo1oSMJ+FW9zZyGDZpQag1cnOJlWtLMROxKG1n5BjDOCRkO4sfSNJVYeiLpJ/t/3VX8mlQIiloDLyA3n+iUrO5LDVfoE3BHQvwt35IO9S3XPgsg9KJvz+trJ0yeiaIlO2Iveiv8TgOR4LYtMzfgfVqx/YZXLZN4v1V3fK86xX+AZIFHZnjmJ1zlI91aUwptXE4weeCBcX89wnPfsnosYCTTaBOQvHMjwmSP6zbzNC/G9YnNetORVF8LGW1cjpxMJqVU9w8ZfHACNsGjfkZ73EXyhuI7bhINmClkcm5ktV/vmEd4HQSjilsOweif3fjSqfZwX0KtfBiqaDcY1TcAmZNAMBhd9MWK3OCdY5ozfblje2Mq3WEYk60A75/RGP+qTHJ9e1hbUZm0UW3H5pVNDuc3RMBuTezbmf+JdC4FagkU2VC3cl6h6pQcR7K1FCWDMrGVdG/ETbnLaSdTOIusafns8G3FQvTHpLY2aOdDp70hoxxIvNMCzsbvGN2G0HDuwK5Bazei6N8zHm1F0sbnCWlVjvBO9GgkJjnIIA99ofDjAaaLNA0M/12NcwRXxUQn4KZ/S+t0TYeHwHls+UE7ksB6bucgQPk=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: test-secret
      namespace: sealed-secrets

